#spring.profile: prod
#google:
#  queryParams:
#    maxResults: 15
#itunes:
#  queryParams:
#    limit: 15
#
#---
#
#spring.profile: dev
#google:
#  queryParams:
#    maxResults: 10
#itunes:
#  queryParams:
#    limit: 10
#---

google:
  endpoint: https://www.googleapis.com/books/v1/volumes
  queryParams:
    maxResults: 5
    orderBy: relevance
    printType: books

itunes:
  endpoint: https://itunes.apple.com/search
  queryParams:
    limit: 5
    attribute: albumTerm
    entity: album

app.response.timeout: 3
management.security.enabled: false